openapi: 3.0.0
info:
  title: Page Prowler API
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        '200':
          description: Server is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles/start:
    post:
      summary: Start the matching process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                URL:
                  type: string
                SearchTerms:
                  type: string
                CrawlSiteID:
                  type: string
                MaxDepth:
                  type: integer
                Debug:
                  type: boolean
      responses:
        '200':
          description: Matching process started
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
