openapi: 3.0.0
info:
  title: Page Prowler API
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
paths:
  /ping:
    get:
      summary: Ping the server
      description: This operation checks if the server is up and running.
      responses:
        "200":
          description: Server is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /matchlinks:
    post:
      summary: Create a new matching task
      description: This operation creates a new matching task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                URL:
                  type: string
                SearchTerms:
                  type: string
                CrawlSiteID:
                  type: string
                MaxDepth:
                  type: integer
                Debug:
                  type: boolean
      responses:
        "201":
          description: Matching task created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"
  /matchlinks/{id}:
    get:
      summary: Get the details of a matching task
      description: This operation retrieves the details of a matching task for a given ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the matching task to retrieve.
      responses:
        "200":
          description: Matching task retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"
  /matchlinks/{id}/delete:
    post:
      summary: Delete the matching task
      description: This operation deletes the matching task for a given ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the matching task to delete.
      responses:
        "200":
          description: Matching task deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          $ref: "#/components/responses/DefaultError"
        "500":
          $ref: "#/components/responses/DefaultError"
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
  responses:
    DefaultError:
      description: An unexpected error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
