version: '3'

tasks:
  build:
    cmds:
      - go build -v -o bin/prowl main.go
    desc: Build the prowl binary

  test:
    cmds:
      - go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
    desc: Run all tests with gotestfmt

  fmt:
    cmds:
      - go fmt ./...
    desc: Format the Go code

  vet:
    cmds:
      - go vet ./...
    desc: Vet the Go code

  lint:
    cmds:
      - golangci-lint run
    desc: Run static analysis

  bench:
    cmds:
      - go test -bench .
    desc: Run benchmarks

  update:
    cmds:
      - go get -u
      - go mod tidy
    desc: Update dependencies

  docker:
    cmds:
      - docker build -t jonesrussell/page-prowler .
    desc: Build Docker image

  clean:
    cmds:
      - rm -rf ./bin
      - rm -f /tmp/gotest.log
      - go clean -cache -testcache -modcache -fuzzcache
    desc: Clean up generated files and Go caches

  default:
    desc: Run default tasks
    deps:
      - clean
      - fmt
      - vet
      - lint
      - test
      - build
