// Package crawler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package crawler

import "testing"

func TestRegisterHandlers(t *testing.T) {
	type args struct {
		router EchoRouter
		si     ServerInterface
	}
	tests := []struct {
		name string
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			RegisterHandlers(tt.args.router, tt.args.si)
		})
	}
}
