// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"

	colly "github.com/gocolly/colly"

	crawler "github.com/jonesrussell/page-prowler/internal/crawler"

	logger "github.com/jonesrussell/page-prowler/internal/logger"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// CrawlManagerInterface is an autogenerated mock type for the CrawlManagerInterface type
type CrawlManagerInterface struct {
	mock.Mock
}

// Crawl provides a mock function with given fields: url, options
func (_m *CrawlManagerInterface) Crawl(url string, options *crawler.CrawlOptions) ([]crawler.PageData, error) {
	ret := _m.Called(url, options)

	if len(ret) == 0 {
		panic("no return value specified for Crawl")
	}

	var r0 []crawler.PageData
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *crawler.CrawlOptions) ([]crawler.PageData, error)); ok {
		return rf(url, options)
	}
	if rf, ok := ret.Get(0).(func(string, *crawler.CrawlOptions) []crawler.PageData); ok {
		r0 = rf(url, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crawler.PageData)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *crawler.CrawlOptions) error); ok {
		r1 = rf(url, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CrawlURL provides a mock function with given fields: url
func (_m *CrawlManagerInterface) CrawlURL(url string) error {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for CrawlURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCrawlingMu provides a mock function with given fields:
func (_m *CrawlManagerInterface) GetCrawlingMu() *sync.Mutex {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCrawlingMu")
	}

	var r0 *sync.Mutex
	if rf, ok := ret.Get(0).(func() *sync.Mutex); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.Mutex)
		}
	}

	return r0
}

// HandleVisitError provides a mock function with given fields: url, err
func (_m *CrawlManagerInterface) HandleVisitError(url string, err error) error {
	ret := _m.Called(url, err)

	if len(ret) == 0 {
		panic("no return value specified for HandleVisitError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, error) error); ok {
		r0 = rf(url, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogError provides a mock function with given fields: message, keysAndValues
func (_m *CrawlManagerInterface) LogError(message string, keysAndValues ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, keysAndValues...)
	_m.Called(_ca...)
}

// Logger provides a mock function with given fields:
func (_m *CrawlManagerInterface) Logger() logger.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 logger.Logger
	if rf, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}

	return r0
}

// NewCollector provides a mock function with given fields:
func (_m *CrawlManagerInterface) NewCollector() *colly.Collector {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewCollector")
	}

	var r0 *colly.Collector
	if rf, ok := ret.Get(0).(func() *colly.Collector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*colly.Collector)
		}
	}

	return r0
}

// ProcessMatchingLinkAndUpdateStats provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *CrawlManagerInterface) ProcessMatchingLinkAndUpdateStats(_a0 *crawler.CrawlOptions, _a1 string, _a2 crawler.PageData, _a3 []string) {
	_m.Called(_a0, _a1, _a2, _a3)
}

// SetupCrawlingLogic provides a mock function with given fields: _a0
func (_m *CrawlManagerInterface) SetupCrawlingLogic(_a0 *crawler.CrawlOptions) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetupCrawlingLogic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*crawler.CrawlOptions) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetupErrorEventHandler provides a mock function with given fields: collector
func (_m *CrawlManagerInterface) SetupErrorEventHandler(collector *colly.Collector) {
	_m.Called(collector)
}

// SetupHTMLParsingHandler provides a mock function with given fields: handler
func (_m *CrawlManagerInterface) SetupHTMLParsingHandler(handler func(*colly.HTMLElement)) error {
	ret := _m.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for SetupHTMLParsingHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*colly.HTMLElement)) error); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartCrawling provides a mock function with given fields: ctx, url, searchterms, siteid, maxdepth, debug
func (_m *CrawlManagerInterface) StartCrawling(ctx context.Context, url string, searchterms string, siteid string, maxdepth int, debug bool) error {
	ret := _m.Called(ctx, url, searchterms, siteid, maxdepth, debug)

	if len(ret) == 0 {
		panic("no return value specified for StartCrawling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, bool) error); ok {
		r0 = rf(ctx, url, searchterms, siteid, maxdepth, debug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCrawlManagerInterface creates a new instance of CrawlManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrawlManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CrawlManagerInterface {
	mock := &CrawlManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
