name: A workflow for Streetcode Crawler / Consumer
on: push

jobs:
  build:
    name: Streetcode action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2 # Use version 2 of the setup-go action
        with:
          go-version: '1.19' # Specify the desired Go version here
          check-latest: true
      - run: go run cmd/crawler/main.go --url=www.cp24.com --search=toronto
      