name: A workflow for Crawler

on: push

jobs:
  build:
    name: Crawler action
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_AUTH=" >> .env
          echo "REDIS_STREAM=crawler" >> .env
          echo "REDIS_DB=1" >> .env
          # Add other environment variables as needed
        working-directory: ${{ github.workspace }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Change to the required Go version
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Add golangci-lint to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Lint
        run: golangci-lint run ./...

      - name: Build
        run: go build ./...

      - name: Run Tests
        run: go test ./...
