name: A workflow for Crawler

on: push

jobs:
  build:
    name: Crawler action
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_AUTH=" >> .env
          echo "REDIS_STREAM=crawler" >> .env
          echo "REDIS_DB=1" >> .env
          # Add other environment variables as needed
        working-directory: ${{ github.workspace }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19' # Change to the required Go version
          check-latest: true

      - name: Run Tests
        run: go test ./...
